version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "local-rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "local-rabbit"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq # Persist RabbitMQ data
      - ./rabbitmq/logs:/var/log/rabbitmq # Persist RabbitMQ logs

